### ISSUE TITLE
Test editor tools

### ISSUE THREAD

**Issue by o2carr68** [o2carr68/test-01#3]
Tracking the testing of  the **following** tools
- [x] Add header test (Covered below)
- [x] Insert a quote (Covered in #4)
- [x] Insert code (Covered in #5)
- [x] Add a link (Covered in #5)
- [x] Insert saved reply (Covered in #5)
- [x] Mention a user or team (Covered in #5)
- [x] Reference an issue or pull request (Covered in #5 and here)

**Comment by o2carr68** [comment]
# Add header test
Some additional headers

## First part
Nothing important.


## Second part
Nothing important.
